### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by methodmissing** [spreedly/r2d2#9]
@rwdaigle any plans to ship this to rubygems.org as well?

**Comment by rwdaigle** [comment]
@methodmissing no concrete plans yet - is your concern a deployment related one - or discover related?

**Comment by methodmissing** [comment]
Deployment - not a huge deal - was just curious.

**Comment by rwdaigle** [comment]
Yep, I see no reason (besides time) *not* to do it 👍

**Comment by rwdaigle** [comment]
Better late than never?

https://rubygems.org/gems/r2d2
